version: 2

defaults: &defaults
  macos:
    xcode: "10.0.0"

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Reset Simulators
          command: |
              export LC_ALL=en_US.UTF-8
              export LANG=en_US.UTF-8
              fastlane snapshot reset_simulators --force

      - run:
          name: Run Tests
          command: make test
